[workspace]
members = [
    "ownable",
    "metadata",
    "token",
    "sellable",
    "redeemable",
    "sales",
    "allowable"
]

[workspace.dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = "1.1.3"
cosmwasm-storage = "1.1.3"
cw-storage-plus = "0.16.0"
cw2 = "0.15.1"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
serde_json = "1.0.87"
thiserror = { version = "1.0.31" }
burnt-glue = "0.2.2"
semver = "1.0.14"
cw721-base = "0.16.0"
ownable = { path = "./ownable" }
allowable = { path = "./allowable" }
token = { path = "./token" }
redeemable = { path = "./redeemable" }
sellable = { path = "./sellable" }
